import { Tool } from "./types";

export const aiTools: Tool[] = [
  { id: "ai-writer", name: "AI Writer", description: "Generate articles, blogs, emails with AI", iconName: "PenTool", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-paraphraser", name: "AI Paraphraser", description: "Rephrase text while keeping the meaning", iconName: "RefreshCw", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "text-input" },
  { id: "ai-translator", name: "AI Translator", description: "Translate text between 100+ languages", iconName: "Globe2", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "dual-text" },
  { id: "ai-chatbot", name: "AI Chatbot", description: "Chat with an advanced GPT-4 AI assistant", iconName: "Bot", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-code-assistant", name: "AI Code Assistant", description: "Get AI help with coding and debugging", iconName: "Code2", category: "ai", isAI: true, isPremium: true, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "code-editor" },
  { id: "ai-resume-builder", name: "AI Resume Builder", description: "Create professional resumes with AI", iconName: "FileUser", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-presentation", name: "AI Presentation Maker", description: "Generate beautiful presentations with AI", iconName: "Presentation", category: "ai", isAI: true, isPremium: true, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-summarizer", name: "AI Summarizer", description: "Summarize any text, article or document", iconName: "FileSearch", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "text-input" },
  { id: "ai-grammar-check", name: "Grammar Checker", description: "Fix grammar, spelling and punctuation with AI", iconName: "SpellCheck", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "text-input" },
  { id: "ai-email-writer", name: "AI Email Writer", description: "Draft professional emails in seconds", iconName: "Mail", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-cover-letter", name: "Cover Letter Generator", description: "Create tailored cover letters with AI", iconName: "FileHeart", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-content-ideas", name: "Content Idea Generator", description: "Generate viral content ideas for any niche", iconName: "Lightbulb", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-story-gen", name: "AI Story Generator", description: "Write compelling stories and narratives", iconName: "BookOpen", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "prompt-only" },
  { id: "ai-sentiment", name: "Sentiment Analyzer", description: "Analyze sentiment and tone of any text", iconName: "BarChart3", category: "ai", isAI: true, isPremium: false, color: "#6366F1", gradient: "linear-gradient(135deg, #6366F1, #818CF8)", uiType: "text-input" },
];

export const developerTools: Tool[] = [
  { id: "json-formatter", name: "JSON Formatter", description: "Format, validate and minify JSON data", iconName: "Braces", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "code-editor" },
  { id: "regex-tester", name: "Regex Tester", description: "Test and debug regular expressions live", iconName: "Regex", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "dual-text" },
  { id: "jwt-decoder", name: "JWT Decoder", description: "Decode, inspect and verify JWT tokens", iconName: "Key", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "text-input" },
  { id: "base64-encoder", name: "Base64 Encoder/Decoder", description: "Encode and decode Base64 strings", iconName: "Lock", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "dual-text" },
  { id: "uuid-generator", name: "UUID Generator", description: "Generate unique UUIDs v1, v4, v5", iconName: "Fingerprint", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "calculator" },
  { id: "color-picker", name: "Color Picker", description: "Pick and convert colors between HEX, RGB, HSL", iconName: "Palette", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "calculator" },
  { id: "hash-generator", name: "Hash Generator", description: "Generate MD5, SHA-1, SHA-256 hashes", iconName: "Hash", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "text-input" },
  { id: "markdown-editor", name: "Markdown Editor", description: "Write and preview Markdown in real-time", iconName: "FileJson", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "dual-text" },
  { id: "url-encoder", name: "URL Encoder/Decoder", description: "Encode and decode URLs and query strings", iconName: "Link", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "dual-text" },
  { id: "html-formatter", name: "HTML Formatter", description: "Format and beautify HTML code", iconName: "Code", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "code-editor" },
  { id: "css-minifier", name: "CSS Minifier", description: "Minify and compress CSS code", iconName: "Minimize2", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "code-editor" },
  { id: "js-minifier", name: "JS Minifier", description: "Minify JavaScript for faster loading", iconName: "Zap", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "code-editor" },
  { id: "ai-code-review", name: "AI Code Review", description: "Get AI-powered code reviews and suggestions", iconName: "GitBranch", category: "developer", isAI: true, isPremium: true, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "code-editor" },
  { id: "sql-formatter", name: "SQL Formatter", description: "Format and beautify SQL queries", iconName: "Database", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "code-editor" },
  { id: "cron-generator", name: "Cron Expression Generator", description: "Build and validate cron expressions visually", iconName: "Timer", category: "developer", isAI: false, isPremium: false, color: "#14B8A6", gradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)", uiType: "calculator" },
];
