import { Tool } from "./types";

export const imageTools: Tool[] = [
  { id: "bg-remover", name: "Background Remover", description: "Remove image backgrounds instantly with AI", iconName: "UserMinus", category: "image", isAI: true, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "ai-enhancer", name: "AI Image Enhancer", description: "Enhance photo quality and sharpness using AI", iconName: "Zap", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "ai-upscaler", name: "AI Upscaler", description: "Upscale images 4x without quality loss", iconName: "Maximize2", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "ai-art-gen", name: "AI Art Generator", description: "Generate stunning artwork from text prompts", iconName: "Brush", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "prompt-image" },
  { id: "ai-logo-gen", name: "AI Logo Generator", description: "Create professional logos with AI", iconName: "Crown", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "prompt-image" },
  { id: "image-compress", name: "Image Compressor", description: "Compress images while maintaining quality", iconName: "FileArchive", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "multi-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp,.gif" },
  { id: "resize-image", name: "Resize Image", description: "Resize images to any dimension", iconName: "Ruler", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "crop-image", name: "Crop Image", description: "Crop images to any size or aspect ratio", iconName: "Crop", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "convert-image", name: "Image Converter", description: "Convert between JPG, PNG, WebP, AVIF formats", iconName: "RefreshCw", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "multi-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp,.gif,.bmp" },
  { id: "watermark-image", name: "Add Watermark", description: "Add text or image watermarks to photos", iconName: "Stamp", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "file-text-input", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "ai-colorize", name: "AI Photo Colorizer", description: "Colorize black & white photos with AI", iconName: "Palette", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png" },
  { id: "ai-restore", name: "AI Photo Restorer", description: "Restore and repair old or damaged photos", iconName: "Wand2", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png" },
  { id: "meme-gen", name: "Meme Generator", description: "Create viral memes with custom text", iconName: "Smile", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "file-text-input", acceptedFiles: ".jpg,.jpeg,.png" },
  { id: "collage-maker", name: "Collage Maker", description: "Create beautiful photo collages", iconName: "LayoutGrid", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "multi-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "image-to-text", name: "Image to Text (OCR)", description: "Extract text from any image with AI", iconName: "ScanText", category: "image", isAI: true, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "qr-from-image", name: "QR Code Scanner", description: "Scan and decode QR codes from images", iconName: "QrCode", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "face-blur", name: "Face Blur", description: "Automatically blur faces in photos for privacy", iconName: "EyeOff", category: "image", isAI: true, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png" },
  { id: "flip-rotate-image", name: "Flip & Rotate", description: "Flip and rotate images instantly", iconName: "FlipHorizontal", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "image-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "ai-avatar-gen", name: "AI Avatar Generator", description: "Generate professional AI avatars from your photo", iconName: "UserCircle", category: "image", isAI: true, isPremium: true, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "prompt-image" },
  { id: "svg-to-png", name: "SVG to PNG", description: "Convert SVG vector files to PNG raster images", iconName: "Shapes", category: "image", isAI: false, isPremium: false, color: "#8B5CF6", gradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)", uiType: "file-upload", acceptedFiles: ".svg" },
];
