import { Tool } from "./types";

export const pdfTools: Tool[] = [
  { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to editable Word files", iconName: "FileEdit", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "word-to-pdf", name: "Word to PDF", description: "Convert Word documents to PDF", iconName: "FileText", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".doc,.docx" },
  { id: "merge-pdf", name: "Merge PDF", description: "Combine multiple PDFs into one", iconName: "Combine", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "multi-upload", acceptedFiles: ".pdf" },
  { id: "split-pdf", name: "Split PDF", description: "Split a PDF into separate pages or ranges", iconName: "Scissors", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "compress-pdf", name: "Compress PDF", description: "Reduce PDF size without quality loss", iconName: "FileArchive", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "ocr-pdf", name: "OCR PDF", description: "Extract text from scanned PDFs using AI", iconName: "ScanText", category: "pdf", isAI: true, isPremium: true, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf,.jpg,.png" },
  { id: "sign-pdf", name: "Sign PDF", description: "Add digital signatures to PDF documents", iconName: "PenTool", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "pdf-chat", name: "AI PDF Chat", description: "Chat with your PDF using AI", iconName: "MessageSquareText", category: "pdf", isAI: true, isPremium: true, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-chat", acceptedFiles: ".pdf" },
  { id: "pdf-to-jpg", name: "PDF to JPG", description: "Convert PDF pages to JPG images", iconName: "Image", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "jpg-to-pdf", name: "JPG to PDF", description: "Convert images to PDF format", iconName: "FileImage", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "multi-upload", acceptedFiles: ".jpg,.jpeg,.png,.webp" },
  { id: "pdf-to-excel", name: "PDF to Excel", description: "Convert PDF tables to Excel spreadsheets", iconName: "Table", category: "pdf", isAI: true, isPremium: true, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "protect-pdf", name: "Protect PDF", description: "Add password protection to PDF files", iconName: "Lock", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-password", acceptedFiles: ".pdf" },
  { id: "unlock-pdf", name: "Unlock PDF", description: "Remove password from protected PDFs", iconName: "Unlock", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-password", acceptedFiles: ".pdf" },
  { id: "rotate-pdf", name: "Rotate PDF", description: "Rotate PDF pages to any angle", iconName: "RotateCw", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "watermark-pdf", name: "Watermark PDF", description: "Add custom watermarks to PDF files", iconName: "Stamp", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-text-input", acceptedFiles: ".pdf" },
  { id: "pdf-summarizer", name: "AI PDF Summarizer", description: "Get an AI-powered summary of any PDF", iconName: "BookOpen", category: "pdf", isAI: true, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "reorder-pdf", name: "Reorder PDF Pages", description: "Drag and drop to reorder PDF pages", iconName: "GripVertical", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "delete-pdf-pages", name: "Delete PDF Pages", description: "Remove specific pages from a PDF", iconName: "Trash2", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "pdf-to-ppt", name: "PDF to PowerPoint", description: "Convert PDF to editable presentations", iconName: "Presentation", category: "pdf", isAI: true, isPremium: true, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
  { id: "flatten-pdf", name: "Flatten PDF", description: "Flatten form fields and annotations", iconName: "Layers", category: "pdf", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "file-upload", acceptedFiles: ".pdf" },
];
