import { Tool } from "./types";

export const businessTools: Tool[] = [
  { id: "invoice-gen", name: "Invoice Generator", description: "Create professional invoices instantly", iconName: "Receipt", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "calculator" },
  { id: "qr-gen", name: "QR Code Generator", description: "Generate custom QR codes for any URL", iconName: "QrCode", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "text-input" },
  { id: "barcode-gen", name: "Barcode Generator", description: "Generate EAN, UPC, QR barcodes", iconName: "Barcode", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "text-input" },
  { id: "tax-calc", name: "Tax Calculator", description: "Calculate taxes for any jurisdiction", iconName: "Calculator", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "calculator" },
  { id: "ai-business-plan", name: "AI Business Plan Generator", description: "Generate a full business plan with AI", iconName: "BriefcaseBusiness", category: "business", isAI: true, isPremium: true, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "prompt-only" },
  { id: "ai-proposal", name: "AI Proposal Writer", description: "Write winning business proposals with AI", iconName: "FileSignature", category: "business", isAI: true, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "prompt-only" },
  { id: "ai-contract", name: "AI Contract Generator", description: "Generate legal contracts and agreements with AI", iconName: "FileCheck", category: "business", isAI: true, isPremium: true, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "prompt-only" },
  { id: "expense-tracker", name: "Expense Tracker", description: "Track and categorize business expenses", iconName: "Wallet", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "calculator" },
  { id: "currency-converter", name: "Currency Converter", description: "Convert currencies with live exchange rates", iconName: "Coins", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "calculator" },
  { id: "roi-calculator", name: "ROI Calculator", description: "Calculate return on investment instantly", iconName: "TrendingUp", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "calculator" },
  { id: "email-signature", name: "Email Signature Generator", description: "Create professional email signatures", iconName: "Signature", category: "business", isAI: false, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "calculator" },
  { id: "ai-job-description", name: "AI Job Description Writer", description: "Write compelling job descriptions with AI", iconName: "ClipboardList", category: "business", isAI: true, isPremium: false, color: "#3B82F6", gradient: "linear-gradient(135deg, #3B82F6, #60A5FA)", uiType: "prompt-only" },
];

export const marketingTools: Tool[] = [
  { id: "ai-ad-copy", name: "AI Ad Copy Generator", description: "Generate high-converting ad copy with AI", iconName: "Megaphone", category: "marketing", isAI: true, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
  { id: "ai-seo-meta", name: "SEO Meta Generator", description: "Generate SEO-optimized meta titles and descriptions", iconName: "Search", category: "marketing", isAI: true, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
  { id: "ai-hashtag-gen", name: "Hashtag Generator", description: "Generate trending hashtags for any post", iconName: "Hash", category: "marketing", isAI: true, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
  { id: "ai-social-post", name: "Social Media Post Generator", description: "Create engaging posts for LinkedIn, Twitter, IG", iconName: "Share2", category: "marketing", isAI: true, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
  { id: "ai-product-desc", name: "Product Description Writer", description: "Write compelling e-commerce descriptions", iconName: "ShoppingBag", category: "marketing", isAI: true, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
  { id: "ai-blog-outline", name: "Blog Outline Generator", description: "Create detailed blog post outlines with AI", iconName: "List", category: "marketing", isAI: true, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
  { id: "utm-builder", name: "UTM Link Builder", description: "Build UTM-tagged URLs for campaign tracking", iconName: "Link", category: "marketing", isAI: false, isPremium: false, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "calculator" },
  { id: "ai-press-release", name: "Press Release Writer", description: "Write professional press releases with AI", iconName: "Newspaper", category: "marketing", isAI: true, isPremium: true, color: "#EC4899", gradient: "linear-gradient(135deg, #EC4899, #F472B6)", uiType: "prompt-only" },
];
