import { Tool } from "./types";

export const studentTools: Tool[] = [
  { id: "ai-essay-writer", name: "AI Essay Writer", description: "Write structured academic essays with AI", iconName: "GraduationCap", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "prompt-only" },
  { id: "citation-gen", name: "Citation Generator", description: "Generate APA, MLA, Chicago citations", iconName: "BookMarked", category: "student", isAI: false, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "ai-flashcards", name: "AI Flashcard Generator", description: "Turn notes into study flashcards automatically", iconName: "Layers", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "ai-quiz-gen", name: "AI Quiz Generator", description: "Generate quizzes from any topic or text", iconName: "HelpCircle", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "prompt-only" },
  { id: "math-solver", name: "Math Problem Solver", description: "Solve complex math with step-by-step solutions", iconName: "Calculator", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "ai-note-taker", name: "AI Note Taker", description: "Turn lectures into structured notes with AI", iconName: "NotebookPen", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "plagiarism-check", name: "Plagiarism Checker", description: "Check for plagiarism in your writing", iconName: "ShieldCheck", category: "student", isAI: true, isPremium: true, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "study-planner", name: "AI Study Planner", description: "Create personalized study schedules with AI", iconName: "CalendarDays", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "prompt-only" },
  { id: "ai-explainer", name: "AI Concept Explainer", description: "Get any complex topic explained simply", iconName: "Lightbulb", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "prompt-only" },
  { id: "word-counter", name: "Word Counter", description: "Count words, characters, sentences and reading time", iconName: "AlignLeft", category: "student", isAI: false, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "grammar-check-student", name: "Essay Grammar Checker", description: "Fix grammar mistakes in your essays", iconName: "SpellCheck", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "text-input" },
  { id: "ai-thesis-gen", name: "Thesis Statement Generator", description: "Generate strong thesis statements with AI", iconName: "FileText", category: "student", isAI: true, isPremium: false, color: "#F59E0B", gradient: "linear-gradient(135deg, #F59E0B, #FBBF24)", uiType: "prompt-only" },
];

export const dailyLifeTools: Tool[] = [
  { id: "bmi-calc", name: "BMI Calculator", description: "Calculate your Body Mass Index and health range", iconName: "Scale", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "unit-converter", name: "Unit Converter", description: "Convert length, weight, temperature and more", iconName: "Ruler", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "password-gen", name: "Password Generator", description: "Generate secure, strong passwords instantly", iconName: "ShieldCheck", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "pomodoro", name: "Pomodoro Timer", description: "Boost productivity with the Pomodoro technique", iconName: "Timer", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "notes-app", name: "Quick Notes", description: "Take fast notes with auto-save", iconName: "StickyNote", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "text-input" },
  { id: "age-calculator", name: "Age Calculator", description: "Calculate exact age from birthdate", iconName: "CalendarDays", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "loan-calculator", name: "Loan Calculator", description: "Calculate monthly payments and total interest", iconName: "Landmark", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "tip-calculator", name: "Tip Calculator", description: "Calculate tips and split bills easily", iconName: "Utensils", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
  { id: "ip-lookup", name: "IP Lookup", description: "Look up IP address details and geolocation", iconName: "MapPin", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "text-input" },
  { id: "random-gen", name: "Random Generator", description: "Generate random numbers, names, colors", iconName: "Shuffle", category: "health", isAI: false, isPremium: false, color: "#F43F5E", gradient: "linear-gradient(135deg, #F43F5E, #FB7185)", uiType: "calculator" },
];

export const hrTools: Tool[] = [
  { id: "ai-interview-questions", name: "AI Interview Questions", description: "Generate tailored interview questions with AI", iconName: "MessageSquare", category: "hr", isAI: true, isPremium: false, color: "#0EA5E9", gradient: "linear-gradient(135deg, #0EA5E9, #38BDF8)", uiType: "prompt-only" },
  { id: "ai-resume-screener", name: "AI Resume Screener", description: "Screen and rank resumes with AI", iconName: "FileSearch", category: "hr", isAI: true, isPremium: true, color: "#0EA5E9", gradient: "linear-gradient(135deg, #0EA5E9, #38BDF8)", uiType: "file-upload", acceptedFiles: ".pdf,.doc,.docx" },
  { id: "ai-offer-letter", name: "Offer Letter Generator", description: "Generate professional offer letters with AI", iconName: "FileCheck", category: "hr", isAI: true, isPremium: false, color: "#0EA5E9", gradient: "linear-gradient(135deg, #0EA5E9, #38BDF8)", uiType: "prompt-only" },
  { id: "salary-calculator", name: "Salary Calculator", description: "Calculate salaries with deductions and benefits", iconName: "Wallet", category: "hr", isAI: false, isPremium: false, color: "#0EA5E9", gradient: "linear-gradient(135deg, #0EA5E9, #38BDF8)", uiType: "calculator" },
  { id: "ai-performance-review", name: "Performance Review Writer", description: "Generate fair performance reviews with AI", iconName: "ClipboardCheck", category: "hr", isAI: true, isPremium: true, color: "#0EA5E9", gradient: "linear-gradient(135deg, #0EA5E9, #38BDF8)", uiType: "prompt-only" },
];
