import { Tool } from "./types";

export const videoTools: Tool[] = [
  { id: "video-compress", name: "Video Compressor", description: "Compress videos without quality loss", iconName: "FileArchive", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi,.mkv,.webm" },
  { id: "video-to-mp3", name: "Video to MP3", description: "Extract audio from any video file", iconName: "Music", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi,.mkv,.webm" },
  { id: "trim-video", name: "Trim Video", description: "Cut and trim video clips precisely", iconName: "Scissors", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi,.mkv" },
  { id: "ai-subtitles", name: "AI Subtitles Generator", description: "Auto-generate subtitles in 50+ languages", iconName: "Captions", category: "video", isAI: true, isPremium: true, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.mkv" },
  { id: "ai-reels", name: "AI Reels Generator", description: "Create viral short clips from long videos", iconName: "Smartphone", category: "video", isAI: true, isPremium: true, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.mkv" },
  { id: "gif-maker", name: "GIF Maker", description: "Convert video clips to animated GIFs", iconName: "PlayCircle", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi" },
  { id: "screen-recorder", name: "Screen Recorder", description: "Record your screen directly in browser", iconName: "Monitor", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "no-input" },
  { id: "merge-videos", name: "Merge Videos", description: "Combine multiple video files into one", iconName: "Combine", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "multi-upload", acceptedFiles: ".mp4,.mov,.avi,.mkv" },
  { id: "video-convert", name: "Video Converter", description: "Convert between MP4, MOV, AVI, MKV and more", iconName: "RefreshCw", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi,.mkv,.webm,.flv" },
  { id: "video-watermark", name: "Video Watermark", description: "Add text or logo watermarks to videos", iconName: "Stamp", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-text-input", acceptedFiles: ".mp4,.mov,.avi" },
  { id: "video-screenshot", name: "Video Screenshot", description: "Extract specific frames from video as images", iconName: "Camera", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi,.mkv" },
  { id: "video-speed", name: "Video Speed Changer", description: "Speed up or slow down any video", iconName: "Gauge", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi" },
  { id: "ai-video-summary", name: "AI Video Summary", description: "Get a text summary of any video with AI", iconName: "FileSearch", category: "video", isAI: true, isPremium: true, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.mkv" },
  { id: "video-reverse", name: "Reverse Video", description: "Play video in reverse for creative effects", iconName: "Rewind", category: "video", isAI: false, isPremium: false, color: "#06B6D4", gradient: "linear-gradient(135deg, #06B6D4, #22D3EE)", uiType: "file-upload", acceptedFiles: ".mp4,.mov,.avi" },
];

export const audioTools: Tool[] = [
  { id: "speech-to-text", name: "Speech to Text", description: "Transcribe audio to text with AI accuracy", iconName: "Mic2", category: "audio", isAI: true, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg,.flac" },
  { id: "text-to-speech", name: "Text to Speech", description: "Convert text to natural-sounding speech", iconName: "Volume2", category: "audio", isAI: true, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "prompt-only" },
  { id: "voice-cloning", name: "AI Voice Cloning", description: "Clone any voice with advanced AI models", iconName: "Users", category: "audio", isAI: true, isPremium: true, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a" },
  { id: "noise-remover", name: "Noise Remover", description: "Remove background noise from recordings", iconName: "VolumeX", category: "audio", isAI: true, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg" },
  { id: "ai-music-gen", name: "AI Music Generator", description: "Generate original royalty-free music with AI", iconName: "Music2", category: "audio", isAI: true, isPremium: true, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "prompt-only" },
  { id: "audio-trim", name: "Audio Trimmer", description: "Cut and trim audio files precisely", iconName: "Scissors", category: "audio", isAI: false, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg,.flac" },
  { id: "audio-merge", name: "Audio Merger", description: "Combine multiple audio files into one", iconName: "Combine", category: "audio", isAI: false, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "multi-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg" },
  { id: "audio-convert", name: "Audio Converter", description: "Convert between MP3, WAV, FLAC, AAC and more", iconName: "RefreshCw", category: "audio", isAI: false, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg,.flac,.aac" },
  { id: "audio-speed", name: "Audio Speed Changer", description: "Speed up or slow down audio files", iconName: "Gauge", category: "audio", isAI: false, isPremium: false, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg" },
  { id: "podcast-transcript", name: "Podcast Transcriber", description: "Get full transcripts of any podcast", iconName: "FileText", category: "audio", isAI: true, isPremium: true, color: "#10B981", gradient: "linear-gradient(135deg, #10B981, #34D399)", uiType: "file-upload", acceptedFiles: ".mp3,.wav,.m4a,.ogg" },
];
